---
- name: Add 127.0.0.1 as an A record for cats.internet.local
  win_hosts:
    state: present
    canonical_name: cats.internet.local
    ip_address: 127.0.0.1

- name: Enable IIS on Virtual Machines
  win_feature:
    name: Web-Server
    state: present
    include_sub_features: yes
    include_management_tools: yes
  register: win_feature

- name: Create directory structure
  win_file:
    path: C:\sites\demo\
    state: directory

- name: Copy index.html to specified path only if modified
  win_copy:
    src: files/index.html
    dest: C:\sites\demo\index.html
    force: yes

- name: Copy cats.jpg to specified path only if modified
  win_copy:
    src: files/cats.jpg
    dest: C:\sites\demo\images\cats.jpg
    force: yes

- name: Remove the default http binding
  win_iis_webbinding:
    name: Default Web Site
    port: 80
    ip: '*'
    state: absent

# Remove Default Web Site and the standard port 80 binding
- name: Remove Default Web Site
  win_iis_website:
    name: "Default Web Site"
    state: absent

- name: Demo IIS site
  win_iis_website:
    name: Demo Web Site
    state: started
    port: 80
    protocol: http
    ip: "*"
    hostname: cats.internet.local
    physical_path: C:\sites\demo
    parameters: logfile.directory:C:\sites\logs
  register: website

- name: Add a HTTPS binding
  win_iis_webbinding:
    name: Demo Web Site
    protocol: https
    port: 80
    ip: "*"
    state: present

- name: Create Firewall Rule Port 80
  win_firewall_rule:
    name: "allow http in"
    localport: "80"
    action: allow
    direction: in
    protocol: tcp
    state: present
    enabled: yes

- name: Create Firewall Rule Port 443
  win_firewall_rule:
    name: "allow https in"
    localport: "443"
    action: allow
    direction: in
    protocol: tcp
    state: present
    enabled: yes

- name: Reboot Machine
  win_reboot:
  when: win_feature.reboot_required
